version: '3.8'

networks:
  sourpopcorn-webapp-network:
    driver: bridge

services:
  sourpopcorn-webapp:
    image: docker.io/library/webapp
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=https://localhost:8081
    ports:
      - '7070:7070'
    restart: always
    volumes:
      - .:/usr/src/app
    command: ['pnpm', 'run', 'dev']
