version: '3.8'

networks:
  sourpopcorn-webapp-network:
    driver: bridge

services:
  sourpopcorn-webapp:
    image: docker.io/library/webapp
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '7070:7070'
    volumes:
      - .:/usr/src/app
    command: ['pnpm', 'run', 'dev']
